version: '3.8'

services:
  # PostgreSQLサービス
  db:
    image: postgres:14
    container_name: item-manager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: items_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - item-network

  # Express.jsアプリケーションサービス
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: item-manager-app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: items_db
      DB_PORT: 5432
      NODE_ENV: development
      PORT: 9999
    ports:
      - "8111:9999"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - db
    networks:
      - item-network

networks:
  item-network:
    driver: bridge
